# Generated by Django 6.0.1 on 2026-01-08 06:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_pdf', models.FileField(upload_to='documents/')),
                ('file_size', models.PositiveIntegerField()),
                ('page_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='api_documen_created_2fddfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='api_signatu_created_227857_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_pdf', models.FileField(upload_to='signed_documents/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
            options={
                'indexes': [models.Index(fields=['signed_at'], name='api_signedd_signed__e1f105_idx'), models.Index(fields=['original_document'], name='api_signedd_origina_c2a027_idx')],
            },
        ),
    ]
