# Generated by Django 6.0.1 on 2026-01-08 06:49

import api.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.signature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='original_pdf',
            field=models.FileField(upload_to='documents/', validators=[api.validators.validate_pdf_file, api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='signature',
            name='image_file',
            field=models.ImageField(upload_to='signatures/', validators=[api.validators.validate_image_file, api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='signed_pdf',
            field=models.FileField(upload_to='signed_documents/', validators=[api.validators.validate_pdf_file, api.validators.validate_file_size]),
        ),
        migrations.AddIndex(
            model_name='signeddocument',
            index=models.Index(fields=['signature'], name='api_signedd_signatu_1c4326_idx'),
        ),
    ]
