# Generated by Django 6.0.1 on 2026-01-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_signeddocument_signature_alter_document_original_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='signeddocument',
            options={'ordering': ['-signed_at']},
        ),
    ]
